name: Update README projects table

on:
  schedule:
    - cron: '8 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run script
        run: python scripts/update_readme_projects.py

      - name: Commit and push changes
        run: |
          git config --local user.email "mzafram2001@gmail.com"
          git config --local user.name "mzafram2001"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "auto: Update README table" && git push)
